name: WeChat Reminder

on:
  schedule:
    - cron: '0 1 * * *'   # 北京时间 9点
    - cron: '0 10 * * *'  # 北京时间 18点
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send WeChat Message
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7fcad4df-7206-48f9-8318-afae72cf5722' \
          -H 'Content-Type: application/json' \
          -d '{
            "msgtype": "text",
            "text": {
              "content": "@所有人 各位同事，和作社打卡时间到了，别忘记打卡哦～"
            }
          }'
